//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csi.see.classlib1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Integrated Security=True;Persist Security Info=False;Pooling=False;Data Source=.\\" +
            "SQLEXPRESS;Initial Catalog=master")]
        public string sqlConnect_master {
            get {
                return ((string)(this["sqlConnect_master"]));
            }
            set {
                this["sqlConnect_master"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Integrated Security=True;Persist Security Info=False;Pooling=False;Data Source=.\\" +
            "SQLEXPRESS;Initial Catalog=SeeCommon")]
        public string sqlConnect_common {
            get {
                return ((string)(this["sqlConnect_common"]));
            }
            set {
                this["sqlConnect_common"] = value;
            }
        }
    }
}
